In [1]:
#Q1

l1 = ["aman","222",777,400.4]

t = tuple(l1)
print(t)
print(type(t))

('aman', '222', 777, 400.4)
<class 'tuple'>


In [2]:
#Q2

dictonary = {'Roll No' : 'cb.en.u4cse20269' , 'Last name' : 'Nagoor' , 'First name' : 'Veeraboina' , 'Date of birth' : '06-09-2002'}
print('Dictionary : ',dictonary)
print('KEYS : ',dictonary.keys())
print('VALUES : ',dictonary.values())

Dictionary :  {'Roll No': 'cb.en.u4cse20269', 'Last name': 'Nagoor', 'First name': 'Veeraboina', 'Date of birth': '06-09-2002'}
KEYS :  dict_keys(['Roll No', 'Last name', 'First name', 'Date of birth'])
VALUES :  dict_values(['cb.en.u4cse20269', 'Nagoor', 'Veeraboina', '06-09-2002'])


In [3]:
#Q3

import numpy as np
import random
random.seed(50)
d2 = np.random.rand(2,2)
print(d2)

[[0.59710364 0.56512023]
 [0.27951899 0.0977371 ]]


In [4]:
#Q4

import random
randnum = random.uniform(0.0,1.0)
print(randnum)
import math
no = -1234
print(abs(-1234))

0.4975365687586023
1234


In [5]:
#Q5

import random
randnum = random.randint(20,90)
print(randnum)

54


In [6]:
#Q6

import random
population = [11,12,13,14,15]
#3numset
print(random.sample(population,3))
#shuffle
random.shuffle(population)
print(population)
#randprint
print(random.choice(population))

[13, 12, 15]
[15, 12, 11, 13, 14]
12


In [7]:
#Q7 
file=open("test.txt","w")
file.write("The King is Dead, Long Live The King")
file.close()
file=open("test.txt","r")
for i in file:
  print(i,end=" ")

The King is Dead, Long Live The King 

In [8]:
#Q8

def ist(n,ch):
  if ch in ['s','S']:
    print('Square of the given number is : ',n**2)
  elif ch in ['c','C']:
    print('Cube of the given number is : ',n**3)
  elif ch in ['f','F']:
    print('Factorial of the given number is : ',fac(n))
  else:
    print('Invalid Choice')

def fac(n):
  f=1
  for i in range(1,n+1):
    f*=i
  return f

print("Enter a choice :")
ch = input('s for square\nc for cube\nf for factorial of the given number : ')
n = int(input('Enter the number : '))
ist(n,ch)

Enter a choice :
s for square
c for cube
f for factorial of the given number : 54
Enter the number : 12
Invalid Choice


In [9]:
#Q9. 

st = "The King is Dead, Long Live The King"
#1
print(st)
#2
print(st[0])
#3
print(st[2:5])
#4
print(st[2:])
#5
st_list = st.split()
print(st_list)

The King is Dead, Long Live The King
T
e K
e King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


In [10]:
#Q10
import numpy as np
li = [1,4,5,8]
array = np.array(li,dtype=float)
print("Array : ",array)
print("Sliced array : ",array[0:2])

Array :  [1. 4. 5. 8.]
Sliced array :  [1. 4.]


In [11]:
#Q11
import numpy as np
a1 = [1,2,3]
a2 = [4,5,6]
array = np.array((a1,a2))
array

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
#Q12

import numpy as np
a=[1,2,3]
b=[4,5,6]
arr = np.array((a,b),dtype =float)
#2ndrow
print('Second row : ',arr[1:,:])
#2,5
print('Splitted array : ',arr[:,1])
#length
print('Length of the array : ',len(arr))
#shape
print('Shape of the array : ',arr.shape)
#number of elements
tup=arr.shape
leng = 1
for i in tup:
    leng = leng*i
print('Number of elements : ',leng)

Second row :  [[4. 5. 6.]]
Splitted array :  [2. 5.]
Length of the array :  2
Shape of the array :  (2, 3)
Number of elements :  6


In [13]:
#Q13
import numpy as np
li = [1,2,3,4,5,6,7,8,9,10]
arr = np.array(li)
print('Array : \n',arr, '\nShape : ',arr.shape)
narr = arr.reshape(2,5)
print('New Array : \n',narr,'\nShape : ',narr.shape)
print('Transpose of the matrix : \n',narr.transpose())

Array : 
 [ 1  2  3  4  5  6  7  8  9 10] 
Shape :  (10,)
New Array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 
Shape :  (2, 5)
Transpose of the matrix : 
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [14]:
#Q14
import numpy as np
lis = [1,2,3]
nparr = np.array(lis)
print('Array : ',nparr,'\nType : ',type(nparr))

Array :  [1 2 3] 
Type :  <class 'numpy.ndarray'>


In [15]:
#Q15
import numpy as np
l = [1,2,3]
arr = np.array(l)
print('Initail array : ',arr)
arr[:]=9
print('Final array : ',arr)

Initail array :  [1 2 3]
Final array :  [9 9 9]


In [16]:
#Q16
import numpy as np
arr = np.array([2,4,5])
print('Sum of the elements : ', np.sum(arr))

Sum of the elements :  11


In [17]:
#Q17
import numpy as np
arr = np.array([77,74,75])
print('Product of the elements : ',np.product(arr))

Product of the elements :  427350


In [18]:
#Q18
import numpy as np
arr = np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
#mean
print('mean: ',np.mean(arr))
#median
print('median: ',np.median(arr))
#variance
print('variance: ',np.var(arr))
#max
print('Max : ',np.max(arr))
#min
print('Min ',np.min(arr))
#argmin
print('Argmin : ',np.argmin(arr))
#argmax
print('Argmax: ',np.argmax(arr))
#std
print('Standard Deviation: ',np.std(arr))

mean:  12.461538461538462
median:  2.0
variance:  367.32544378698225
Max :  56
Min  1
Argmin :  1
Argmax:  12
Standard Deviation:  19.165736192147232


In [19]:
#Q19
import numpy as np
l = [1,1,4,5,5,5,7]
arr = np.array(l)
unq = np.unique(arr)
print(unq)
s_unq = np.sort(unq)
print(s_unq)

[1 4 5 7]
[1 4 5 7]


In [20]:
#Q20
import numpy as np
a1 = [1,2,3]
a2 = [0,1,1]
a3 = np.dot(a1,a2)
print(a3)

5


In [21]:
#Q21
import numpy as np
A = [[2,-12],[1,-5]]
arr = np.array(A)
eva,eve = np.linalg.eig(A)
print(eva)
print(eve)

[-1. -2.]
[[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]


In [22]:
#Q22
import numpy as np
arr = np.array([[11, 22, 11, 31], [25, 33, 31, 28]],dtype=float)
print(np.corrcoef(arr))

[[1.         0.15997968]
 [0.15997968 1.        ]]
